### ISSUE TITLE
don't return 0 price

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/dexstats_sqlite_py#18]
atm the endpoint https://stats-api.atomicdex.io/api/v1/summary shows 0 prices like this
```
last_price | "0.0000000000"
lowest_ask | "184.7832308222"
highest_bid | "161.1189388062"
base_currency | "KMD"
base_volume | "0.0000000000"
quote_currency | "THC"
quote_volume | "0.0000000000"
price_change_percent_24h | "0.0000000000"
highest_price_24h | "0.0000000000"
lowest_price_24h | "0.0000000000"
pair_liqudity_usd | 55.425287193803534
```
`last_price` 0... this happens when there was no trade in the last 24h.
Problem is that coinpaprika removes those pairs. This is what they wrote me:
"... If they want to have all pairs, they must ensure that the price in the endpoint https://stats-api.atomicdex.io/api/v1/summary is non-zero. They disappear just because of the price of 0.0. We do not support displaying for zero prices."
And once removed, those pairs don't come back, no matter if there was a trade in the last 24h or not.

I propose to change our endpoint so that it always shows the last price in `last_price`, no matter if the last trade was made in the last 24h or not. The volume can stay at 0 if no trade in the last 24h, but not the price.

![image](https://github.com/KomodoPlatform/dexstats_sqlite_py/assets/32116761/15fe86cd-d9ad-4676-a502-a658fbcc3072)
This is an example how it should be... no trades in the last 24h, so volume is 0, but price is NOT 0, it's the last price.

We should do the same. This will also solve the problem that all our pairs disappear after 24h if no trade. It will extend this time to 3 days afaik... maybe we could even extend this to 7 days (if possible without big performance impact).

**Comment by smk762** [comment]
Implemented in https://github.com/KomodoPlatform/dexstats_sqlite_py/tree/stats-api-atomicdex-io-update
