### ISSUE TITLE
Handle more tokens for combined liquidity calculation

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/dexstats_sqlite_py#4]
QRC20
PLG20
ARB20
HRC20
HCO20
AVX20
FTM20
KRC20
OPT20
MVR20

**Comment by smk762** [comment]
Implemented in https://github.com/KomodoPlatform/dexstats_sqlite_py/blob/stats-api-atomicdex-io-update/stats_utils.py#L123-L141
